use std::{path::{Path,PathBuf},sync::Mutex};
use serde::{Serialize,Deserialize};
use serde_json::{Value,json};
use tauri::Manager;
use chrono::{Utc,DateTime,Datelike};
use crate::{database::Database,data_root::DataRoot};
static SERIAL:Mutex<()>=Mutex::new(());
#[derive(Clone,Serialize,Deserialize)]#[serde(rename_all="camelCase")]
struct Record{path:String,created_at:String,items:usize,fingerprint:String,automatic:bool}
#[derive(Clone,Serialize,Deserialize)]#[serde(rename_all="camelCase")]
struct Config{enabled:bool,directory:String,last_fingerprint:String,last_automatic:Option<String>,records:Vec<Record>,status:String,error:String}
fn config_path(app:&tauri::AppHandle)->PathBuf{app.state::<DataRoot>().0.join("automatic-backups.json")}
fn load(app:&tauri::AppHandle)->Result<Config,String>{let path=config_path(app);if path.exists(){return serde_json::from_slice(&std::fs::read(path).map_err(|e|e.to_string())?).map_err(|e|format!("备份登记文件无法读取：{e}"));}let root=app.state::<DataRoot>();let dir=root.0.parent().unwrap_or(&root.0).join("backups");Ok(Config{enabled:true,directory:dir.to_string_lossy().into_owned(),last_fingerprint:String::new(),last_automatic:None,records:vec![],status:String::new(),error:String::new()})}
fn save(app:&tauri::AppHandle,c:&Config)->Result<(),String>{use std::io::Write;let path=config_path(app);let tmp=path.with_extension(format!("{}.tmp",uuid::Uuid::new_v4()));let result=(||{let mut f=std::fs::OpenOptions::new().create_new(true).write(true).open(&tmp).map_err(|e|e.to_string())?;f.write_all(&serde_json::to_vec_pretty(c).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;f.sync_all().map_err(|e|e.to_string())?;drop(f);std::fs::rename(&tmp,&path).map_err(|e|e.to_string())})();if result.is_err(){let _=std::fs::remove_file(tmp);}result}
fn validate_directory(p:&Path)->Result<(),String>{if !p.is_absolute()||p.to_string_lossy().to_ascii_lowercase().starts_with("c:"){return Err("请选择非 C 盘的绝对目录".into());}for ancestor in p.ancestors(){if let Ok(m)=std::fs::symlink_metadata(ancestor){use std::os::windows::fs::MetadataExt;if m.file_attributes()&0x400!=0{return Err("备份目录不能经过目录联接或符号链接".into());}}}Ok(())}
fn preferences(c:&rusqlite::Connection)->Value{c.query_row("SELECT value FROM app_settings WHERE key='appearance'",[],|r|r.get::<_,String>(0)).ok().and_then(|s|serde_json::from_str(&s).ok()).unwrap_or(json!({"theme":"warm_apricot","fontSize":"standard"}))}
fn retention(records:&[Record],now:DateTime<Utc>)->Vec<bool>{
 let mut keep=vec![true;records.len()];let mut weeks=std::collections::HashSet::new();let mut order=(0..records.len()).collect::<Vec<_>>();order.sort_by(|a,b|records[*b].created_at.cmp(&records[*a].created_at));
 for i in order{let r=&records[i];if !r.automatic{continue;}let Ok(time)=DateTime::parse_from_rfc3339(&r.created_at)else{continue;};let age=now.signed_duration_since(time);if age.num_days()<7{continue;}let week=time.iso_week();let key=(week.year(),week.week());keep[i]=age.num_days()<35&&weeks.len()<4&&weeks.insert(key);}keep
}
// 仅操作登记的自动文件，校验路径、内容及无链接；新备份验证完成后才清理。
fn prune(c:&mut Config,now:DateTime<Utc>){let keep=retention(&c.records,now);let base=Path::new(&c.directory);let mut remaining=Vec::new();for(r,keep)in c.records.drain(..).zip(keep){if keep{remaining.push(r);continue;}let p=Path::new(&r.path);let safe=p.parent()==Some(base)&&p.file_name().is_some_and(|s|s.to_string_lossy().starts_with("轻笺自动-"))&&validate_directory(p).is_ok();let verified=crate::backup::read(&r.path).is_ok_and(|b|crate::backup::content_fingerprint(&b)==r.fingerprint);if !safe||!verified||std::fs::remove_file(p).is_err(){remaining.push(r);}}c.records=remaining;}
fn perform(app:&tauri::AppHandle,force:bool)->Result<Value,String>{perform_at(app,force,Utc::now())}
fn perform_at(app:&tauri::AppHandle,force:bool,now:DateTime<Utc>)->Result<Value,String>{let _serial=SERIAL.lock().map_err(|_|"备份状态不可用")?;let mut config=load(app)?;if !force&&!config.enabled{return Ok(json!(config));}
 if !force&&config.last_automatic.as_deref().and_then(|s|DateTime::parse_from_rfc3339(s).ok()).is_some_and(|t|now.signed_duration_since(t).num_seconds()<3600){return Ok(json!(config));}
 let db=app.state::<Database>();let conn=db.0.lock().map_err(|_|"数据库不可用")?;let mut b=crate::backup::snapshot(&conn,preferences(&conn))?;drop(conn);crate::backup::set_created_at(&mut b,now.to_rfc3339());let fingerprint=crate::backup::content_fingerprint(&b);
 if !force&&((crate::backup::item_count(&b)==0&&config.last_fingerprint.is_empty())||config.last_fingerprint==fingerprint){return Ok(json!(config));}
 let result=(||{let dir=Path::new(&config.directory);validate_directory(dir)?;std::fs::create_dir_all(dir).map_err(|e|e.to_string())?;let path=dir.join(format!("轻笺{}-{}-{}.qjbackup",if force{"立即"}else{"自动"},now.format("%Y%m%d-%H%M%S"),uuid::Uuid::new_v4()));crate::backup::write(&path,&b)?;let verified=crate::backup::read(&path.to_string_lossy())?;if crate::backup::content_fingerprint(&verified)!=fingerprint{return Err("备份校验失败".to_string());}
 config.records.push(Record{path:path.to_string_lossy().into_owned(),created_at:now.to_rfc3339(),items:crate::backup::item_count(&b),fingerprint:fingerprint.clone(),automatic:!force});config.last_fingerprint=fingerprint;if !force{config.last_automatic=Some(now.to_rfc3339());}config.status="备份已完成".into();config.error.clear();prune(&mut config,now);Ok(())})();if let Err(error)=result{config.status="备份失败".into();config.error=error;save(app,&config)?;return Ok(json!(config));}save(app,&config)?;Ok(json!(config))
}
#[tauri::command]pub fn auto_backup_status(app:tauri::AppHandle)->Result<Value,String>{let _serial=SERIAL.lock().map_err(|_|"备份状态不可用")?;Ok(json!(load(&app)?))}
// 可控日期仅允许隔离测试进程使用，生产数据根目录和普通运行一律拒绝。
#[tauri::command]pub async fn test_auto_backup_tick(app:tauri::AppHandle,now:String)->Result<Value,String>{let root=app.state::<DataRoot>().0.clone();if std::env::var("QINGJIAN_TEST_MODE").as_deref()!=Ok("1")||!root.to_string_lossy().replace('\\',"/").to_lowercase().contains("/isolated-test/"){return Err("可控日期仅适用于隔离验收".into());}let now=DateTime::parse_from_rfc3339(&now).map_err(|_|"测试日期无效")?.with_timezone(&Utc);tauri::async_runtime::spawn_blocking(move||perform_at(&app,false,now)).await.map_err(|e|e.to_string())?}
#[tauri::command]pub fn backup_preferences(app:tauri::AppHandle,preferences:Value)->Result<(),String>{let db=app.state::<Database>();let c=db.0.lock().map_err(|_|"数据库不可用")?;crate::backup::snapshot(&c,preferences.clone())?;c.execute("INSERT INTO app_settings(key,value) VALUES('appearance',?1) ON CONFLICT(key) DO UPDATE SET value=excluded.value",[preferences.to_string()]).map_err(|e|e.to_string())?;Ok(())}
#[tauri::command]pub async fn backup_now(app:tauri::AppHandle)->Result<Value,String>{tauri::async_runtime::spawn_blocking(move||perform(&app,true)).await.map_err(|e|e.to_string())?}
#[tauri::command]pub async fn configure_auto_backup(app:tauri::AppHandle,enabled:bool,directory:Option<String>,preferences:Value)->Result<Value,String>{
 {let _serial=SERIAL.lock().map_err(|_|"备份状态不可用")?;let mut c=load(&app)?;if let Some(dir)=directory{validate_directory(Path::new(&dir))?;c.directory=dir;}let newly=enabled&&!c.enabled;c.enabled=enabled;if newly{c.last_automatic=None;}save(&app,&c)?;let db=app.state::<Database>();db.0.lock().map_err(|_|"数据库不可用")?.execute("INSERT INTO app_settings(key,value) VALUES('appearance',?1) ON CONFLICT(key) DO UPDATE SET value=excluded.value",[preferences.to_string()]).map_err(|e|e.to_string())?;}
 tauri::async_runtime::spawn_blocking(move||perform(&app,false)).await.map_err(|e|e.to_string())?
}
#[tauri::command]pub fn open_backup_folder(app:tauri::AppHandle)->Result<(),String>{let dir=load(&app)?.directory;validate_directory(Path::new(&dir))?;std::fs::create_dir_all(&dir).map_err(|e|e.to_string())?;std::process::Command::new("explorer.exe").arg(dir).spawn().map_err(|e|e.to_string())?;Ok(())}
pub fn start(app:tauri::AppHandle){std::thread::Builder::new().name("qingjian-automatic-backup".into()).spawn(move||{std::thread::sleep(std::time::Duration::from_secs(2));loop{let _=perform(&app,false);std::thread::sleep(std::time::Duration::from_secs(30));}}).ok();}
#[cfg(test)]mod tests{use super::*;#[test]fn retention_keeps_manual_and_weekly(){let now=DateTime::parse_from_rfc3339("2026-10-05T00:00:00Z").unwrap().with_timezone(&Utc);let rows=(0..50).map(|i|Record{path:String::new(),created_at:(now-chrono::Duration::days(i)).to_rfc3339(),items:1,fingerprint:String::new(),automatic:true}).collect::<Vec<_>>();let k=retention(&rows,now);assert!(k[..7].iter().all(|x|*x));assert!(k[35..].iter().all(|x|!*x));assert!(k[7..].iter().filter(|x|**x).count()<=5);let mut manual=rows;manual[49].automatic=false;assert!(retention(&manual,now)[49]);}}
