import {useCallback,useEffect,useRef,useState,type MutableRefObject} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {listen} from '@tauri-apps/api/event';
import type {Item} from './item_workspace';

type Segment={id:string;track:string;startMs:number;endMs:number;state:string;text:string;error?:string;edited?:boolean;source?:Source};
type Source={kind?:string;model?:string;endpoint?:string;engine?:string;edited?:boolean;fallbackReason?:string;segments?:Segment[];missingRanges?:unknown[];inputFingerprint?:string;transcriptVersionId?:string};
type Version={id:string;kind:string;engine?:string;createdAt:string;text:string;source?:Source};
export type Recording={id:string;createdAt:string;seconds?:number;durationSeconds?:number|null;state:string;mic:string;system:string;storage?:string;savedDir?:string;error?:string;versions:Version[];segmentJob?:{fingerprint:string;state:string;segments:Segment[]}};
type Header=Pick<Recording,'id'|'createdAt'|'seconds'|'state'|'storage'>;
type Local={root:string;available:boolean;validation?:{transcribed?:boolean}};
type Online={endpoint?:string;model?:string;revision?:string;tested?:boolean;hasKey?:boolean};
type Device={id:string;name:string};
type Track={state:string;peak?:number;error?:string;seconds?:number};
type Status={active:boolean;paused?:boolean;captureStopped?:boolean;id?:string;seconds:number;tracks:Record<string,Track>|null};
type Edit={text?:string;edits?:Record<string,string>};
export type AudioGuard={dirty:()=>boolean;save:()=>Promise<boolean>;discard:()=>void};
const valid=(c:Online)=>!!(c.tested&&c.hasKey&&c.endpoint&&c.model&&c.revision);
const time=(ms:number)=>{const n=Math.floor(ms/1000);return [Math.floor(n/3600),Math.floor(n/60)%60,n%60].map(v=>String(v).padStart(2,'0')).join(':');};
const trackName=(track:string)=>track==='mic'?'麦克风':'系统声音';
const compose=(segments:Segment[],edits:Record<string,string>={})=>segments.filter(s=>s.state==='done'&&(edits[s.id]??s.text).trim()).map(s=>'【'+time(s.startMs)+'–'+time(s.endMs)+' · '+trackName(s.track)+'】\n'+(edits[s.id]??s.text)).join('\n\n');
function sourceName(v?:Version){
 if(!v)return '';const s=v.source;
 if(s){let host='';try{host=new URL(s.endpoint||'').hostname;}catch{/* 本地版本没有在线端点。 */}
  return (s.kind==='local'?'本地 · ':s.kind==='summary'?'文本 · ':s.kind==='online'?'在线 · ':'历史 · ')+(host?host+' / ':'')+(s.model||v.engine||'未记录模型')+(s.edited?' · 已校对':'');}
 return '历史 · '+(v.engine||'未记录模型');
}
export function AudioPanel({open,onActive,onDraft,onConfigure,notes,guardRef}:{open:boolean;onActive:(v:boolean)=>void;onDraft:(text:string,item?:Item)=>void;onConfigure:(tab:'语音'|'模型')=>void;notes:Item[];guardRef:MutableRefObject<AudioGuard|null>}){
 const [status,setStatus]=useState<Status>({active:false,seconds:0,tracks:{}}),[headers,setHeaders]=useState<Header[]>([]),[current,setCurrent]=useState<Recording|null>(null);
 const [transcriptId,setTranscriptId]=useState(''),[summaryId,setSummaryId]=useState(''),[view,setView]=useState<'transcript'|'summary'>('transcript');
 const [drafts,setDrafts]=useState<Record<string,Edit>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [local,setLocal]=useState<Local>({root:'',available:false}),[online,setOnline]=useState<Online>({}),[textModel,setTextModel]=useState<Online>({});
 const [devices,setDevices]=useState<{mic:Device[];system:Device[]}>({mic:[],system:[]}),[mic,setMic]=useState(''),[system,setSystem]=useState(''),[mode,setMode]=useState<'local'|'online'>('local');
 const [preview,setPreview]=useState<Record<string,Track>>({}),[confirm,setConfirm]=useState<'summary'|'transcribe'|'reset'|'discard'|'leave'|null>(null),[destination,setDestination]=useState(false),[output,setOutput]=useState<'transcript'|'summary'|'both'>('transcript'),[target,setTarget]=useState('');
 const [deleteDialog,setDeleteDialog]=useState(false),[deleteAudio,setDeleteAudio]=useState(false);
 const [query,setQuery]=useState(''),[selectedSegment,setSelectedSegment]=useState(''),[scrollTop,setScrollTop]=useState(0),[viewport,setViewport]=useState(300);
 const listRef=useRef<HTMLDivElement>(null),task=useRef(false),activeRef=useRef(false),idRef=useRef(''),loadTicket=useRef(0),openRef=useRef(open),pendingChange=useRef<()=>void>(()=>{});
 openRef.current=open;idRef.current=current?.id||status.id||'';
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),2500);return()=>clearTimeout(timer);},[notice]);
 const reloadHeaders=useCallback(async()=>{const rows=await invoke<Header[]>('list_recording_headers');setHeaders(rows);return rows;},[]);
 const load=useCallback(async(id:string)=>{const ticket=++loadTicket.current;const record=await invoke<Recording>('get_recording',{id});if(ticket===loadTicket.current)setCurrent(record);return record;},[]);
 const deleteCurrent=async()=>{if(!current||task.current)return;const id=current.id;const at=headers.findIndex(h=>h.id===id);task.current=true;setBusy(true);setError('');try{const result=await invoke<{sharedFilesRetained:number;warning?:string}>('delete_recording',{id,deleteAudio});setDeleteDialog(false);idRef.current='';setStatus(s=>({...s,id:''}));setCurrent(null);setDrafts({});setTranscriptId('');setSummaryId('');setSelectedSegment('');setQuery('');setView('transcript');const rows=await reloadHeaders();const next=rows[Math.min(Math.max(at,0),rows.length-1)];if(next){idRef.current=next.id;await load(next.id);}setNotice(result.warning||(result.sharedFilesRetained?'记录已删除，共用音频已保留':'记录已删除'));}catch(e){setError(String(e));}finally{task.current=false;setBusy(false);}};
 const config=useCallback(async()=>{const [l,a,t,d,input]=await Promise.all([invoke<Local>('audio_config'),invoke<Online>('online_config',{kind:'audio'}),invoke<Online>('online_config',{kind:'text'}),invoke<{mic:Device[];system:Device[]}>('audio_devices'),invoke<{micDevice?:string;systemDevice?:string;mode?:'local'|'online'}>('get_recording_inputs')]);setLocal(l);setOnline(a);setTextModel(t);setDevices(d);setMic(input.micDevice||'');setSystem(input.systemDevice||'');if(input.mode)setMode(input.mode);return {l,a,input};},[]);
 useEffect(()=>{let live=true;const poll=async()=>{try{const s=await invoke<Status>('recording_status');if(!live)return;setStatus(s);onActive(s.active);if(s.active&&s.id&&idRef.current!==s.id)void load(s.id);if(activeRef.current&&!s.active&&idRef.current){void load(idRef.current);void reloadHeaders();}activeRef.current=s.active;}catch(e){if(live)setError(String(e));}};void poll();const timer=setInterval(()=>void poll(),500);return()=>{live=false;clearInterval(timer);};},[load,onActive,reloadHeaders]);
 useEffect(()=>{if(open){void reloadHeaders().catch(e=>setError(String(e)));void config().then(({l,a,input})=>{if(!idRef.current&&!input.mode)setMode(l.validation?.transcribed?'local':valid(a)?'online':'local');}).catch(e=>setError(String(e)));}},[open,config,reloadHeaders]);
 useEffect(()=>{const p=listen<{id:string;message:string}>('recording-stage',e=>{if(e.payload.id===idRef.current)setMessage(e.payload.message);});return()=>{void p.then(f=>f());};},[]);
 useEffect(()=>{if(!open||current||status.active||busy)return;let live=true,inFlight=false;const sample=async()=>{if(inFlight)return;inFlight=true;try{const p=await invoke<Record<string,Track>>('preview_audio_inputs',{micDevice:mic||null,systemDevice:system||null});if(live)setPreview(p);}catch{/* 开始录音时仍会报告具体设备错误。 */}finally{inFlight=false;}};void sample();const t=setInterval(()=>void sample(),1800);return()=>{live=false;clearInterval(t);};},[open,current,status.active,busy,mic,system]);
 const transcripts=current?.versions.filter(v=>v.kind!=='summary')||[],summaries=current?.versions.filter(v=>v.kind==='summary')||[];
 const transcript=transcripts.find(v=>v.id===transcriptId)||transcripts.at(-1),summary=summaries.find(v=>v.id===summaryId)||summaries.at(-1),chosen=view==='summary'?summary:transcript;
 const effective=(v?:Version)=>!v?'':v.source?.segments?compose(v.source.segments,drafts[v.id]?.edits):drafts[v.id]?.text??v.text;
 const dirtyVersions=(current?.versions||[]).filter(v=>effective(v)!==v.text),dirty=dirtyVersions.length>0;
 const segments=chosen?.source?.segments||[],edits=chosen?drafts[chosen.id]?.edits||{}:{};
 const filtered=segments.filter(s=>(edits[s.id]??s.text).toLocaleLowerCase().includes(query.toLocaleLowerCase())||trackName(s.track).includes(query));
 const segment=filtered.find(s=>s.id===selectedSegment)||filtered[0];
 const rowHeight=96,first=Math.max(0,Math.floor(scrollTop/rowHeight)-3),last=Math.min(filtered.length,first+Math.ceil(viewport/rowHeight)+7);
 useEffect(()=>{setScrollTop(0);if(listRef.current)listRef.current.scrollTop=0;},[chosen?.id]);
 useEffect(()=>{const el=listRef.current;if(!el)return;const resize=new ResizeObserver(()=>setViewport(el.clientHeight));resize.observe(el);return()=>resize.disconnect();},[open,chosen?.id,segments.length]);
 const refreshCurrent=async()=>{await reloadHeaders();if(idRef.current)await load(idRef.current);};
 const run=async(fn:()=>Promise<void>,label='正在处理…')=>{if(task.current)return;task.current=true;setBusy(true);setMessage(label);setError('');setNotice('');try{await fn();}catch(e){setError(String(e));}finally{try{await refreshCurrent();}catch(e){setError(String(e));}task.current=false;setBusy(false);}};
 const saveAll=async()=>{if(task.current)return false;task.current=true;setBusy(true);setMessage('保存校对…');setError('');try{
  for(const version of dirtyVersions){const result=await invoke<Recording>('save_recording_text',{id:current!.id,versionId:version.id,text:effective(version),edits:drafts[version.id]?.edits||null});setCurrent(result);const saved=result.versions.at(-1)!;if(version.kind==='summary')setSummaryId(saved.id);else setTranscriptId(saved.id);setDrafts(d=>{const next={...d};delete next[version.id];return next;});}
  setNotice('校对已保存');return true;
 }catch(e){setError('保存失败：'+String(e));return false;}finally{task.current=false;setBusy(false);}};
 guardRef.current={dirty:()=>dirty,save:saveAll,discard:()=>setDrafts({})};
 const saveRef=useRef(saveAll);saveRef.current=saveAll;
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(openRef.current&&e.ctrlKey&&!e.altKey&&e.key.toLowerCase()==='s'){e.preventDefault();e.stopPropagation();void saveRef.current();}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);
 const safeChange=(action:()=>void)=>{if(dirty){pendingChange.current=action;setConfirm('leave');}else action();};
 const selectRecord=(id:string)=>safeChange(()=>{setDrafts({});setTranscriptId('');setSummaryId('');setQuery('');setSelectedSegment('');setView('transcript');setError('');setNotice('');if(id){idRef.current=id;void load(id).catch(e=>setError(String(e)));}else{loadTicket.current++;idRef.current='';setStatus(s=>({...s,id:''}));setCurrent(null);}});
 const reset=()=>{loadTicket.current++;setCurrent(null);setStatus(s=>({...s,id:''}));idRef.current='';setTranscriptId('');setSummaryId('');setDrafts({});setQuery('');setSelectedSegment('');setConfirm(null);setView('transcript');setError('');setNotice('');};
 const chooseRoute=async()=>{if(!current)return;await invoke('set_recording_route',{id:current.id,mode,revision:mode==='online'?online.revision||null:null,fallback:mode==='local'&&valid(online)?online.revision:null});};
 const transcribe=async(id:string)=>{if(current?.segmentJob?.state==='complete')await invoke('reset_transcription_job',{id});const r=await invoke<Recording>('transcribe_recording',{id});setCurrent(r);setView('transcript');setTranscriptId('');setSelectedSegment('');};
 // 快速入口只采集音频；不继承在线发送授权，停止后由用户另行确认转写。
 const begin=async(quick=false)=>{
  if(task.current)return;task.current=true;setBusy(true);setError('');setMessage('打开录音设备…');
  try{const active=await invoke<Status>('recording_status');if(active.active){setStatus(active);onActive(true);if(active.id)await load(active.id);return;}
   const cfg=await config();const inputs=quick?cfg.input:{micDevice:mic,systemDevice:system,mode};
   const selectedMic=inputs.micDevice||'',selectedSystem=inputs.systemDevice||'';
   setMic(selectedMic);setSystem(selectedSystem);setMode(inputs.mode||'local');
   const allDevices=await invoke<{mic:Device[];system:Device[]}>('audio_devices');
   if(!allDevices.mic.length||!allDevices.system.length)throw Error('未找到可用录音设备，请连接麦克风并检查 Windows 麦克风权限。');
   if(selectedMic&&!allDevices.mic.some(d=>d.id===selectedMic)||selectedSystem&&!allDevices.system.some(d=>d.id===selectedSystem))throw Error('上次选择的设备已不可用，请在此选择设备后开始录音。');
   await invoke('save_recording_inputs',{micDevice:selectedMic,systemDevice:selectedSystem,mode:inputs.mode||'local'});
   const r=await invoke<Recording>('start_recording',{micDevice:selectedMic||null,systemDevice:selectedSystem||null,mode:'local',onlineRevision:null,fallbackRevision:null});
   setCurrent(r);idRef.current=r.id;setDrafts({});setTranscriptId('');setSummaryId('');onActive(true);setStatus(s=>({...s,active:true,id:r.id,seconds:0,tracks:{}}));
  }catch(e){setError('开始录音失败：'+String(e));}finally{task.current=false;setBusy(false);}
 };
 const requestTranscription=()=>{if(!requireSaved())return;if(mode==='online'||valid(online)){setConfirm('transcribe');return;}void run(async()=>{await chooseRoute();await transcribe(current!.id);},'准备转写…');};
 const requireSaved=()=>{if(dirty){setNotice('请先按 Ctrl+S 保存校对内容');return false;}return true;};
 const outputText=output==='transcript'?effective(transcript):output==='summary'?effective(summary):'# 转写\n\n'+effective(transcript)+'\n\n# 转写纪要\n\n'+effective(summary);
 const source=sourceName(chosen);
 const phase=status.active?(status.paused?'录音已暂停':'正在录音'):busy?message.includes('纪要')?'生成转写纪要':'正在处理':chosen?(view==='summary'?'转写纪要':'校对转写'):current?'录音已暂存':'准备录音';
 const routes=<><label>转写方式<select value={mode} disabled={busy||status.active} onChange={e=>setMode(e.target.value as typeof mode)}><option value="local">本地 SenseVoice</option><option value="online" disabled={!valid(online)}>在线语音模型{!valid(online)?' · 未就绪':''}</option></select></label><p className="audio-model-status">{mode==='local'?'SenseVoiceSmall · '+(local.validation?.transcribed?'可用':local.available?'需检查':'未安装'):(online.model||'未配置')+' · '+(valid(online)?'可用':'未测试')}</p>{mode==='online'?<p className="audio-consent">选择转写并确认后，才会上传音频。</p>:valid(online)&&<p className="audio-consent">选择转写并确认后，本地不可用时才会使用在线语音模型。</p>}</>;
 const recordOptions=current&&!status.active&&!busy&&<details className="audio-options"><summary>录音与历史</summary><div className="audio-options-content">
  {chosen&&<label>历史版本<select aria-label="结果版本" disabled={busy} value={chosen.id} onChange={e=>view==='summary'?setSummaryId(e.target.value):setTranscriptId(e.target.value)}>{(view==='summary'?summaries:transcripts).map(v=><option value={v.id} key={v.id}>{new Date(v.createdAt).toLocaleString('zh-CN')}{v.source?.edited?' · 校对':''}</option>)}</select></label>}
  {current.storage==='saved'?null:current.storage==='discarded'?<p>音频已不保留，文字历史仍可查看。</p>:<><p>音频暂存</p><button onClick={()=>void run(async()=>{setCurrent(await invoke<Recording>('save_recording_audio',{id:current.id}));},'保存录音…')}>保存录音</button>{current.storage==='temporary'&&<button onClick={()=>setConfirm('discard')}>不保留录音</button>}</>}
  {current.storage!=='discarded'&&<><div className="audio-actions">{(['mic','system']as const).map(k=><button key={k} onClick={()=>void invoke('play_recording_at',{id:current.id,track:k,startMs:0,endMs:null}).catch(e=>setError(String(e)))}>重听{trackName(k)}</button>)}<button onClick={()=>void invoke('stop_playback')}>停止播放</button></div>{routes}<button onClick={requestTranscription}>重新转写／重试失败片段</button></>}
  <button onClick={()=>setConfirm('reset')}>重新开始</button>
 </div></details>;
 if(!open)return null;
 return <section className="audio-workspace recording-workspace" aria-label="录音与转写" data-native-dialog-busy={busy&&message.includes('保存录音')?'true':undefined}>
  <header className="recording-top"><div className="recording-title"><h2>{phase}</h2>{!status.active&&!busy&&headers.length>0&&<select aria-label="录音历史" value={current?.id||''} onChange={e=>selectRecord(e.target.value)}><option value="">新录音</option>{headers.map(h=><option key={h.id} value={h.id}>{new Date(h.createdAt).toLocaleString('zh-CN')}{h.state==='interrupted'?' · 已中断':''}</option>)}</select>}</div>
   {busy&&<p className="audio-progress" role="status">{message}</p>}
   {error&&<div className="audio-error" role="alert">{error.split(/[；\n]/)[0].slice(0,100)}{error.length>100&&<details><summary>详细原因</summary>{error}</details>}</div>}
   {notice&&<p className="audio-notice" role="status">{notice}</p>}
   {current?.error&&!error&&!busy&&<p className="audio-error" role="alert">{current.error}</p>}
   {chosen&&!status.active&&<><div className="audio-result-tabs"><button aria-pressed={view==='transcript'} onClick={()=>setView('transcript')}>转写</button><button disabled={!summary} aria-pressed={view==='summary'} onClick={()=>setView('summary')}>纪要</button><span className="recording-duration">{typeof current?.durationSeconds==="number"?"时长 "+time(current.durationSeconds*1000):"时长未知"}</span></div><p className="audio-source" title={source}>{source}{dirty?' · 未保存':''}</p>{!!chosen.source?.missingRanges?.length&&<p className="audio-error">尚有 {chosen.source.missingRanges.length} 段未完成。</p>}</>}
  </header>
  <div className="recording-body">
   {!current&&!status.active&&!busy&&<div className="recording-prepare"><div className="audio-devices">{(['mic','system'] as const).map(k=><label key={k}>{trackName(k)}<select value={k==='mic'?mic:system} onChange={e=>(k==='mic'?setMic:setSystem)(e.target.value)}><option value="">系统默认</option>{devices[k].map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><meter aria-label={trackName(k)+'输入音量'} min={0} max={1} value={preview[k]?.peak||0}/>{preview[k]?.error&&<small role="alert">{preview[k].error}</small>}</label>)}</div><button className="audio-link" onClick={()=>void invoke<{mic:Device[];system:Device[]}>('audio_devices').then(setDevices).catch(e=>setError('刷新设备失败：'+String(e)))}>刷新设备</button><small>系统声音采集扬声器播放的声音。录音保存在本地，转写时另行确认发送。</small>{routes}{!local.validation?.transcribed&&<button className="audio-link" onClick={()=>onConfigure('语音')}>配置语音模型</button>}<details className="recording-history-list"><summary>录音历史 · {headers.length} 条</summary>{headers.length?headers.map(h=><button key={h.id} onClick={()=>selectRecord(h.id)}>{new Date(h.createdAt).toLocaleString('zh-CN')}{h.state==='interrupted'?' · 已中断':''}</button>):<p>暂无录音</p>}</details></div>}
   {status.active&&<div className="recording-live"><div className="audio-timer">{time(status.seconds*1000)}</div>{(['mic','system'] as const).map(k=><div className="recording-meter" key={k}><span>{trackName(k)}</span><meter aria-label={trackName(k)+'录音音量'} min={0} max={1} value={status.tracks?.[k]?.peak||0}/>{status.tracks?.[k]?.error&&<small role="alert">{status.tracks?.[k].error}</small>}</div>)}{status.captureStopped&&<p role="alert">采集已停止，请结束并保留音频。</p>}</div>}
   {!status.active&&chosen&&(segments.length>0?<div className="transcript-layout">
    <div className="transcript-index"><input type="search" aria-label="搜索转写" placeholder="搜索转写" value={query} onChange={e=>{setQuery(e.target.value);setScrollTop(0);if(listRef.current)listRef.current.scrollTop=0;}}/><div className="segment-list" ref={listRef} role="listbox" aria-label="转写时间段" tabIndex={0} onScroll={e=>setScrollTop(e.currentTarget.scrollTop)} onKeyDown={e=>{if(!['ArrowUp','ArrowDown'].includes(e.key)||!filtered.length)return;e.preventDefault();const at=filtered.findIndex(s=>s.id===segment?.id),n=Math.max(0,Math.min(filtered.length-1,at+(e.key==='ArrowDown'?1:-1)));setSelectedSegment(filtered[n].id);e.currentTarget.scrollTop=n*rowHeight;}}>
     <div style={{height:filtered.length*rowHeight,position:'relative'}}>{filtered.slice(first,last).map((s,index)=><button key={s.id} className={'segment-row '+(segment?.id===s.id?'selected':'')} style={{top:(first+index)*rowHeight,height:rowHeight-4}} role="option" aria-selected={segment?.id===s.id} onClick={()=>setSelectedSegment(s.id)}><small>{time(s.startMs)} · {trackName(s.track)}</small><span>{s.state==='done'?(edits[s.id]??s.text)||'未检测到可识别语音':'此段尚未完成'}</span></button>)}</div>
     {!filtered.length&&<p>没有匹配的片段。</p>}
    </div></div>
    <div className="segment-editor">{segment&&<><div className="segment-heading"><small>{time(segment.startMs)}–{time(segment.endMs)} · {trackName(segment.track)}</small><button title="从此时间段播放原音频" disabled={current?.storage==='discarded'} onClick={()=>void invoke('play_recording_at',{id:current!.id,track:segment.track,startMs:segment.startMs,endMs:segment.endMs}).catch(e=>setError(String(e)))}>播放</button><button title="停止播放" onClick={()=>void invoke('stop_playback')}>■</button></div>{segment.state==='done'?<textarea aria-label="校对转写片段" disabled={busy} value={edits[segment.id]??segment.text} onChange={e=>{const text=e.target.value;setDrafts(d=>({...d,[chosen.id]:{...d[chosen.id],edits:{...d[chosen.id]?.edits,[segment.id]:text}}}));}} placeholder="此时间段没有可识别语音。"/>:<div className="segment-failure"><p>{segment.error||'这个片段尚未转写成功。'}</p><button disabled={busy||chosen.source?.inputFingerprint!==current?.segmentJob?.fingerprint} onClick={()=>void run(async()=>{const r=await invoke<Recording>('retry_audio_segment',{id:current!.id,segmentId:segment.id});setCurrent(r);setTranscriptId('');},'重试当前片段…')}>重试这一段</button></div>}</>}</div>
   </div>:<textarea className="audio-result" aria-label={view==='summary'?'编辑转写纪要':'校对转写全文'} disabled={busy} value={effective(chosen)} onChange={e=>{const text=e.target.value;setDrafts(d=>({...d,[chosen.id]:{text}}));}}/>)}
   {!status.active&&current&&!chosen&&!busy&&<div className="recording-recover"><p>音频已保留，尚无转写结果。</p>{routes}<button onClick={requestTranscription}>重试转写</button><button onClick={()=>onConfigure('语音')}>配置语音模型</button></div>}
   {recordOptions}
  </div>
  <footer className="recording-actions">
   {current&&<div className="recording-record-tools"><span title={current.storage==="temporary"||current.storage==="discarded"?"未保存录音":"打开录音目录"}><button className="record-icon" aria-label="打开录音目录" disabled={busy||status.active||current.storage==="temporary"||current.storage==="discarded"} onClick={()=>void invoke("open_recording_folder",{id:current.id}).catch(e=>setError(String(e)))}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 7V5h6l2 2h10v13H3z"/></svg></button></span><button className="record-icon" title="删除记录" aria-label="删除记录" disabled={busy||status.active} onClick={()=>safeChange(()=>{setDeleteAudio(false);setDeleteDialog(true);})}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14M10 10v7M14 10v7"/></svg></button></div>}
   {!current&&!status.active&&!busy&&<button className="audio-primary" disabled={!devices.mic.length||!devices.system.length} onClick={()=>safeChange(()=>void begin())}>开始录音</button>}
   {status.active&&<><button disabled={busy||status.captureStopped} onClick={()=>void invoke('pause_recording',{paused:!status.paused}).catch(e=>setError(String(e)))}>{status.paused?'继续':'暂停'}</button><button className="audio-primary" disabled={busy} onClick={()=>void run(async()=>{const r=await invoke<Recording>('stop_recording');setStatus(s=>({...s,active:false}));onActive(false);setCurrent(r);idRef.current=r.id;},'停止并保留音频…')}>停止录音</button></>}
   {!status.active&&chosen&&!busy&&<><button onClick={()=>void navigator.clipboard.writeText(effective(chosen)).then(()=>setNotice('已复制')).catch(e=>setError(String(e)))}>复制</button>{dirty&&<button onClick={()=>void saveAll()} title="Ctrl+S">保存校对</button>}<button onClick={()=>{if(requireSaved()){setOutput(view);setTarget('');setDestination(true);}}}>保存到笔记</button>{view==='transcript'&&<button className="audio-primary" onClick={()=>{if(!requireSaved())return;if(!valid(textModel)){setNotice('请先配置并测试文字模型');onConfigure('模型');return;}setConfirm('summary');}}>生成转写纪要</button>}</>}
  </footer>
  {deleteDialog&&current&&<div className="dialog-backdrop"><section className="leave-dialog" role="dialog" aria-modal="true" aria-label="删除录音记录"><h2>删除记录？</h2><p>{new Date(current.createdAt).toLocaleString("zh-CN")}</p><p>删除本条转写和纪要。已另存到笔记的内容不受影响。</p>{current.storage!=="discarded"&&<label><input type="checkbox" checked={deleteAudio} disabled={busy} onChange={e=>setDeleteAudio(e.target.checked)}/> 同时删除录音文件</label>}<p>{deleteAudio?"其他记录共用的音频会保留。":"录音文件保留。"}</p>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><button disabled={busy} onClick={()=>void deleteCurrent()}>{busy?"删除中…":"确认删除"}</button><button disabled={busy} onClick={()=>setDeleteDialog(false)}>取消</button></div></section></div>}
  {destination&&<div className="dialog-backdrop"><section className="leave-dialog" role="dialog" aria-modal="true" aria-label="保存到笔记"><h2>保存到笔记</h2><label>内容<select value={output} onChange={e=>setOutput(e.target.value as typeof output)}><option value="transcript" disabled={!transcript}>转写</option><option value="summary" disabled={!summary}>纪要</option><option value="both" disabled={!transcript||!summary}>转写与纪要</option></select></label><label>目标<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">新建笔记</option>{notes.map(n=><option key={n.id} value={n.id}>追加到：{n.title||'无标题笔记'}</option>)}</select></label><textarea readOnly aria-label="写入预览" value={outputText}/><p>生成草稿后，按 Ctrl+S 正式保存；追加不会覆盖原文。</p><div className="dialog-actions"><button onClick={()=>{setDestination(false);onDraft(outputText,notes.find(n=>n.id===target));}}>生成笔记草稿</button><button onClick={()=>setDestination(false)}>取消</button></div></section></div>}
  {confirm&&<div className="dialog-backdrop"><section className="leave-dialog" role="dialog" aria-modal="true" aria-label="确认录音操作"><h2>{confirm==='transcribe'?'确认转写？':confirm==='summary'?'生成转写纪要？':confirm==='discard'?'不保留录音？':confirm==='leave'?'有未保存的校对':'重新开始？'}</h2><p>{confirm==='transcribe'?(mode==='online'?'将向已配置的在线语音服务发送本条录音。':valid(online)?'先使用本地模型；本地不可用时将向已配置在线语音服务发送录音。':'只使用本地语音模型，录音不会发送到在线服务。'):confirm==='summary'?'将向 '+(textModel.model||'文字模型')+' 发送当前已保存转写。':confirm==='discard'?'删除本次暂存双路音频，文字版本与已保存笔记保留。':confirm==='leave'?'要保存当前校对内容吗？':'已保存结果保留在历史；尚未保留的音频继续暂存。'}</p><div className="dialog-actions">
   {confirm==='transcribe'&&<button onClick={()=>{setConfirm(null);void run(async()=>{await chooseRoute();await transcribe(current!.id);},'准备转写…');}}>确认并转写</button>}
   {confirm==='summary'&&<button onClick={()=>{setConfirm(null);void run(async()=>{const r=await invoke<Recording>('process_online',{id:current!.id,kind:'text',text:effective(transcript),confirmedRevision:textModel.revision,sourceVersion:transcript?.id||null});setCurrent(r);setSummaryId('');setView('summary');},'生成转写纪要…');}}>发送并生成</button>}
   {confirm==='discard'&&<button onClick={()=>{setConfirm(null);void run(async()=>{setCurrent(await invoke<Recording>('discard_recording_audio',{id:current!.id}));},'处理临时录音…');}}>不保留</button>}
   {(confirm==='leave'||confirm==='reset')&&<><button onClick={()=>void(async()=>{if(await saveAll()){const action=confirm;setConfirm(null);if(action==='leave')pendingChange.current();else reset();}})()}>{dirty?'保存后继续':confirm==='reset'?'暂留历史并重新开始':'继续'}</button>{dirty&&<button onClick={()=>{const action=confirm;setDrafts({});setConfirm(null);if(action==='leave')pendingChange.current();else reset();}}>放弃修改后继续</button>}</>}
   <button onClick={()=>setConfirm(null)}>取消</button></div></section></div>}
 </section>;
}

