import React,{useEffect,useState,useRef} from 'react';
import {invoke} from '@tauri-apps/api/core';
type Entry={id:string;title:string;kind:string;conflict:boolean;deleted:boolean};
type Preview={checksum:string;createdAt:string;entries:Entry[];items:number;reminders:number;pins:number;conflicts:number;settings:any};
export function BackupRestoreDialog({path,preferences,onClose,onImported}:{path:string;preferences:{theme:string;fontSize:string};onClose:()=>void;onImported:(settings?:any)=>void}){
 const dialog=useRef<HTMLElement>(null);
 const[p,setP]=useState<Preview|null>(null),[selected,setSelected]=useState<string[]>([]),[policy,setPolicy]=useState('skip'),[settings,setSettings]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState('');
 useEffect(()=>{let live=true;setP(null);setSelected([]);setDone('');setError('');setSettings(false);setPolicy('skip');invoke<Preview>('preview_backup',{path}).then(p=>{if(live){setP(p);setSelected(p.entries.map(e=>e.id));}}).catch(e=>{if(live)setError(String(e));});return()=>{live=false;};},[path]);
 useEffect(()=>{const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(!busy)onClose();}if(e.key==='Tab'){const controls=[...dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),select:not(:disabled),input:not(:disabled)')??[]];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',keys,true);dialog.current?.querySelector<HTMLButtonElement>('button')?.focus();return()=>document.removeEventListener('keydown',keys,true);},[busy,onClose]);
 // 内容与公开配置由后端统一校验、备份和事务恢复，避免界面分步提交造成半恢复。
 const restore=async()=>{if(!p||(!selected.length&&!settings)||busy)return;setBusy(true);window.dispatchEvent(new CustomEvent('backup-saving',{detail:true}));setError('');try{const result=await invoke<{imported:number;skipped:number;settings:any;settingsApplied:boolean}>('import_backup',{path,expectedChecksum:p.checksum,policy,preferences,selectedIds:selected,applySettings:settings});if(result.settingsApplied){window.dispatchEvent(new CustomEvent('backup-appearance',{detail:result.settings}));}onImported(result.settingsApplied?result.settings:undefined);setDone(`已恢复 ${result.imported} 条 · 跳过 ${result.skipped} 条`);}catch(e){setError(String(e));}finally{setBusy(false);window.dispatchEvent(new CustomEvent('backup-saving',{detail:false}));}};
 return <div className="dialog-backdrop" data-native-dialog-busy={busy?'true':undefined}><section ref={dialog} className="document-import-dialog" role="dialog" aria-modal="true" aria-label="恢复轻笺备份"><header className="document-import-heading"><h2>恢复预览</h2><button disabled={busy} onClick={onClose}>×</button></header><div className="document-import-content"><p>{path.split(/[\\/]/).at(-1)}</p>{error&&<p role="alert">{error}</p>}{done?<p role="status">{done}</p>:p&&<><p>{new Date(p.createdAt).toLocaleString('zh-CN')} · {p.items} 条内容 · {p.reminders} 个提醒 · {p.pins} 个快捷标签 · {p.conflicts} 个同 ID 冲突</p><p>恢复前自动备份当前内容。默认保留同 ID 的现有内容。</p><label>冲突处理<select value={policy} onChange={e=>setPolicy(e.target.value)} disabled={busy}><option value="skip">跳过冲突，保留现有内容</option><option value="replace">替换选中的同 ID 内容</option></select></label>{policy==='replace'&&<p>确认恢复将替换勾选条目的同 ID 内容。</p>}<label><input type="checkbox" checked={settings} disabled={!p.settings||busy} onChange={e=>setSettings(e.target.checked)}/>同时应用全局设置（不含密钥）</label><div><button onClick={()=>setSelected(p.entries.map(e=>e.id))} disabled={busy}>全选备份内容</button><button onClick={()=>setSelected([])} disabled={busy}>取消全选</button></div>{p.entries.map(e=><label className="import-check" key={e.id}><input type="checkbox" disabled={busy} checked={selected.includes(e.id)} onChange={v=>setSelected(ids=>v.target.checked?[...ids,e.id]:ids.filter(id=>id!==e.id))}/>{e.title||'无标题'} · {e.kind==='note'?'笔记':'便签'}{e.conflict?' · 同 ID 冲突':''}{e.deleted?' · 回收站':''}</label>)}</>}</div><footer className="import-footer"><button disabled={busy} onClick={onClose}>{done?'完成':'取消'}</button>{!done&&<button disabled={busy||!p||(!selected.length&&!settings)} onClick={()=>void restore()}>{busy?'正在备份并恢复…':'确认恢复'}</button>}</footer></section></div>;
}
