import {useEffect,useState} from 'react';
import {useRunState} from './run_session';
import {invoke} from '@tauri-apps/api/core';
type Entry={id:string;kind:string;title:string;updatedAt:string;deleted:boolean;conflict:boolean};
type Preview={checksum:string;entries:Entry[];settings:Record<string,unknown>|null};
function Checklist({entries,selected,setSelected,sessionKey}:{entries:Entry[];selected:string[];setSelected:(s:string[])=>void;sessionKey:string}){
 const [q,setQ]=useRunState(sessionKey+'.query','');return <><input className="backup-search" aria-label="按标题查找" placeholder="按标题查找" value={q} onChange={e=>setQ(e.target.value)}/><div className="file-actions"><button onClick={()=>setSelected(entries.map(e=>e.id))}>全选</button><button onClick={()=>setSelected([])}>取消全选</button><span>已选 {selected.length} / {entries.length}</span></div><div className="backup-entry-list">{entries.filter(e=>e.title.toLowerCase().includes(q.toLowerCase())).map(e=><label key={e.id}><input type="checkbox" checked={selected.includes(e.id)} onChange={v=>setSelected(v.target.checked?[...selected,e.id]:selected.filter(id=>id!==e.id))}/><span><strong>{e.title||('无标题'+(e.kind==='note'?'笔记':'便签'))}</strong><small>{e.kind==='note'?'笔记':'便签'} · {new Date(e.updatedAt).toLocaleDateString()}{e.deleted?' · 回收站':''}{e.conflict?' · 已有同 ID':''}</small></span></label>)}</div></>;
}
export function FileSettings({preferences,onImported}:{preferences:{theme:string;fontSize:string};onImported:(s?:Record<string,unknown>)=>void}){
 const [busy,setBusy]=useRunState('file.busy',false),[message,setMessage]=useRunState('file.message',''),[error,setError]=useRunState('file.error',''),[entries,setEntries]=useRunState<Entry[]>('file.entries',[]),[exportIds,setExportIds]=useRunState<string[]>('file.exportIds',[]),[importIds,setImportIds]=useRunState<string[]>('file.importIds',[]),[path,setPath]=useRunState('file.path',''),[preview,setPreview]=useRunState<Preview|null>('file.preview',null),[policy,setPolicy]=useRunState('file.policy','skip'),[applySettings,setApplySettings]=useRunState('file.applySettings',false),[includeSettings,setIncludeSettings]=useRunState('file.includeSettings',false);
 const reload=()=>invoke<Entry[]>('backup_entries',{preferences}).then(rows=>setEntries(rows.map(e=>({...e,conflict:false}))));useEffect(()=>{void reload().catch(e=>setError(String(e)));},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <section className="file-settings" data-native-dialog-busy={busy||undefined}><h1>备份与恢复</h1><p>新版 .qjbackup 版本 2，可读取版本 1。不包含 API Key、录音原文件与转写历史；不是完整音频备份。此处仅恢复 .qjbackup；普通文档请在便签或笔记中点击“导入”。</p><fieldset disabled={busy}><legend>选择导出内容</legend><Checklist sessionKey="file.export" entries={entries} selected={exportIds} setSelected={setExportIds}/><label className="check-setting"><input type="checkbox" checked={includeSettings} onChange={e=>setIncludeSettings(e.target.checked)}/>同时导出全局主题、字号、窗口与模型公开配置</label><button disabled={!exportIds.length&&!includeSettings} onClick={()=>void run(async()=>{const p=await invoke<string|null>('choose_backup_path',{save:true});if(p)setMessage('导出成功：'+await invoke<string>('export_backup',{path:p,preferences,selectedIds:exportIds,includeSettings}));})}>导出所选</button></fieldset>
 <button disabled={busy} onClick={()=>void run(async()=>{const p=await invoke<string|null>('choose_backup_path',{save:false});if(!p)return;setPreview(await invoke<Preview>('preview_backup',{path:p}));setPath(p);setImportIds([]);setApplySettings(false);setPolicy('skip');})}>选择备份文件</button>{busy&&<p role="status">正在处理…</p>}{error&&<p role="alert" className="error-text">{error}</p>}{message&&<p role="status" className="file-result">{message}</p>}
 {preview&&<fieldset disabled={busy} className="backup-preview"><legend>选择导入内容</legend><Checklist sessionKey="file.import" entries={preview.entries} selected={importIds} setSelected={setImportIds}/><p>所选条目中 {preview.entries.filter(e=>importIds.includes(e.id)&&e.conflict).length} 条同 ID 冲突。</p><label>同 ID 处理<select value={policy} onChange={e=>setPolicy(e.target.value)}><option value="skip">跳过，保留现有内容</option><option value="replace">替换所选同 ID 内容及关联记录</option></select></label>{policy==='replace'&&<p className="error-text">将覆盖所选同 ID 正文、排序、提醒历史和固定关系。</p>}<label className="check-setting"><input type="checkbox" disabled={!preview.settings} checked={applySettings} onChange={e=>setApplySettings(e.target.checked)}/>同时应用全局设置{!preview.settings?'（文件未包含）':''}</label><p>导入前自动备份；错误时整批内容回滚。</p><button disabled={!importIds.length&&!applySettings} onClick={()=>void run(async()=>{const r=await invoke<{imported:number;skipped:number;backupPath:string;settings:Record<string,unknown>|null}>('import_backup',{path,expectedChecksum:preview.checksum,policy,preferences,selectedIds:importIds});let warning='';if(applySettings&&r.settings?.window){try{await invoke('apply_backup_window',{settings:r.settings.window});}catch(e){warning='；内容已恢复，窗口设置失败：'+String(e);}}if(applySettings&&r.settings){try{await invoke("apply_backup_media",{settings:r.settings});}catch(e){warning+="；模型配置应用失败："+String(e);}}onImported(applySettings&&r.settings?r.settings:undefined);await reload();setMessage(`导入 ${r.imported} 条，跳过 ${r.skipped} 条。导入前备份：${r.backupPath}${warning}`);setPreview(null);})}>{policy==='replace'?'确认替换并导入':'确认导入所选'}</button></fieldset>}</section>;
}
