import React,{useEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {BackupRestoreDialog} from './backup_restore';
type State={enabled:boolean;directory:string;status:string;error:string;records:{path:string;createdAt:string;items:number;automatic:boolean}[]};
export function FileSettings({preferences,onImported}:{preferences:{theme:string;fontSize:string};onImported:(settings?:any)=>void}){
 const[state,setState]=useState<State|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[restore,setRestore]=useState<string|null>(null);
 const read=()=>invoke<State>('auto_backup_status').then(setState).catch(e=>setError(String(e)));
 useEffect(()=>{void read();const timer=setInterval(()=>void read(),3000);return()=>clearInterval(timer);},[]);
 const action=async(command:string,args?:any)=>{setBusy(true);setError('');try{const next=await invoke<State>(command,args);setState(next);}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <section className="file-settings"><h2>自动备份</h2><p>备份全部便签、笔记、提醒、置顶关系和必要配置。不包含 API 密钥、新闻缓存、模型、录音原文件或转写历史。</p><label className="window-setting-row"><span>自动备份<small>有变化时每小时最多一次，仅在轻笺运行期间执行。</small></span><input aria-label="自动备份" type="checkbox" checked={state?.enabled??true} disabled={busy||!state} onChange={e=>void action('configure_auto_backup',{enabled:e.target.checked,directory:null,preferences})}/></label><p role="status">{state?.status||'等待内容变化'}{state?.records.length?` · 最近备份 ${new Date(state.records.at(-1)!.createdAt).toLocaleString('zh-CN')}`:''}</p><p>{state?.directory}</p><div className="import-toolbar"><button disabled={busy||!state} onClick={async()=>{const directory=await invoke<string|null>('choose_export_folder');if(directory)void action('configure_auto_backup',{enabled:state!.enabled,directory,preferences});}}>更改保存位置</button><button disabled={busy} onClick={()=>void action('backup_now')}>立即备份</button><button onClick={()=>void invoke('open_backup_folder').catch(e=>setError(String(e)))}>打开文件夹</button></div>{(error||state?.error)&&<><p role="alert">备份未完成：{error||state?.error}</p><button disabled={busy} onClick={()=>void action('backup_now')}>重试</button></>}<p>自动备份保留最近 7 天及此前 4 周每周一份。仅清理登记的自动备份，手动导出文件不受影响。</p><h3>备份记录</h3>{state?.records.slice().reverse().map(r=><div className="bell-row" key={r.path}><span>{new Date(r.createdAt).toLocaleString('zh-CN')} · {r.items} 条 · {r.automatic?'自动':'立即备份'}</span><button disabled={busy} onClick={()=>setRestore(r.path)}>恢复…</button></div>)}<button onClick={async()=>{const path=await invoke<string|null>('choose_backup_path',{save:false});if(path)setRestore(path);}}>恢复其他备份…</button>{restore&&<BackupRestoreDialog path={restore} preferences={preferences} onClose={()=>setRestore(null)} onImported={onImported}/>}</section>;
}
