import {useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
type Row={id:string;title:string};
// 列表工具只收藏缓存内容；确认前不写库，关闭预览不触发更新。
export function NewsCollection({source,rows,selected,onView}:{source:'news'|'model';rows:Row[];selected?:string;onView:(id:string)=>void}){
 const [menu,setMenu]=useState(false),[kind,setKind]=useState<'sticky'|'note'|null>(null),[ids,setIds]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{items:{id:string;kind:string}[]}|null>(null);
 const label=source==='news'?'AI 新闻':'模型资讯';
 const begin=(target:'sticky'|'note')=>{setMenu(false);setKind(target);setIds(selected?[selected]:[]);setError('');setResult(null);};
 return <><div className="item-list-toolbar news-list-toolbar"><small>{label} · {rows.length}条</small><button aria-label={label+'列表操作'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>⋯</button>{menu&&<><button className="list-menu-dismiss" aria-label="关闭资讯菜单" onClick={()=>setMenu(false)}/><div className="list-actions-menu" role="menu"><button disabled={!rows.length} onClick={()=>begin('sticky')}>加入便签…</button><button disabled={!rows.length} onClick={()=>begin('note')}>加入笔记…</button></div></>}</div>
 {kind&&<section className="news-collection-mode" aria-label="加入资讯"><header className="document-import-heading"><h2>加入{kind==='sticky'?'便签':'笔记'}</h2><button disabled={busy} aria-label="关闭加入资讯" onClick={()=>setKind(null)}>×</button></header><div className="document-import-content">{result?<p role="status">已加入 {result.items.length} 条{kind==='sticky'?'便签':'笔记'}</p>:<><label className="import-check"><input type="checkbox" checked={!!rows.length&&rows.every(r=>ids.includes(r.id))} onChange={e=>setIds(e.target.checked?rows.map(r=>r.id):[])}/>全选当前列表（{rows.length}条）</label>{rows.map(r=><label className="export-item-row" key={r.id}><input type="checkbox" disabled={busy} checked={ids.includes(r.id)} onChange={e=>setIds(s=>e.target.checked?[...s,r.id]:s.filter(id=>id!==r.id))}/><strong>{r.title}</strong></label>)}</>}{error&&<p role="alert">{error}</p>}</div><footer className="document-import-actions"><small>已选 {rows.filter(r=>ids.includes(r.id)).length} 条</small><button disabled={busy} onClick={()=>setKind(null)}>{result?'完成':'取消'}</button>{result?<button onClick={()=>{const id=result.items[0]?.id;setKind(null);if(id)onView(id);}}>查看内容</button>:<button disabled={busy||!ids.length} onClick={()=>void(async()=>{setBusy(true);setError('');try{const preferences={theme:document.documentElement.dataset.theme||'warm_apricot',fontSize:document.documentElement.dataset.fontSize||'standard'};setResult(await invoke('collect_news',{source,kind,ids:ids.filter(id=>rows.some(r=>r.id===id)),preferences}));}catch(e){setError('加入失败：'+String(e));}finally{setBusy(false);}})()}>{busy?'正在保存…':'确认加入'}</button>}</footer></section>}</>;
}
